### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [13, 6] at entry 0 and [131, 6] at entry 1

### ISSUE THREAD

**Issue by tslgithub** [imLabNTU/VIUNet#1]
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 145, in collate
    return elem_type([collate(samples, collate_fn_map=collate_fn_map) for samples in transposed])
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 145, in <listcomp>
    return elem_type([collate(samples, collate_fn_map=collate_fn_map) for samples in transposed])
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 145, in collate
    return elem_type([collate(samples, collate_fn_map=collate_fn_map) for samples in transposed])
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 145, in <listcomp>
    return elem_type([collate(samples, collate_fn_map=collate_fn_map) for samples in transposed])
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 171, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/accer2/viunet-env/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [13, 6] at entry 0 and [131, 6] at entry 1

**Comment by tslgithub** [comment]
when I run python train.py,  it occured the error.

**Comment by Homura852** [comment]
hi，bro。if you have save this question?
